### ISSUE TITLE
Parameter polygon

### ISSUE THREAD

**Issue by dani-s-92** [jerskisnow/Polygon-Arbitrage-Bot#4]
Hello,

can someone tell me which abis to use for polygon? The same than ethereum abis?

thank you!

**Comment by OnlyF0uR** [comment]
They are already hardcoded into the [utils](https://github.com/OnlyF0uR/Polygon-Arbitrage-Bot/blob/main/src/utils.ts#L98). But yeah in essence they should be the same. Note that this project is perhaps slightly outdated and requires some technical knowledge to make it work in accordance with your expectations.
