### ISSUE TITLE
gas error

### ISSUE THREAD

**Issue by nervodatascience** [jerskisnow/Polygon-Arbitrage-Bot#6]
** reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":8150,"error":{"code":-32000,"message":"exceeds block gas limit"}}',
  error: Error: exceeds block gas limit**

**Comment by OnlyF0uR** [comment]
It seems to me that the error is quite self-explanatory: "exceeds block gas limit". So the gas limit is too low in order to fully pay for all the computation required for the contract to execute.

**Comment by nervodatascience** [comment]
I increased the gas limit to 6718946 and now the transaction is being mined.... 

it worked after implementing in the code 


 **await cntr.functions.execute(dat, ethers.utils.parseUnits('20000', 18), { gasLimit: process.env.GAS_LIMIT, gasPrice: process.env.GAS_PRICE , nonce: await getNonce(signer.address) }).catch(console.error)**;


but now the transaction has an error *fail* in execution
